### ISSUE TITLE
Can the schedule begin from today instead of from yesterday?

### ISSUE THREAD

**Issue by easypickings** [xmcp/pku-eutopia#1]
Yesterday's records seem to have no use... 🤔

**Comment by xmcp** [comment]
The design motivation is that yesterday's registration records might be helpful (i.e. when you want to repeat yesterday's trip). Since that we have a preference page now, I will add a checkbox to toggle this behavior.

**Comment by xmcp** [comment]
implemented in the latest build (220918.171600)
